version: '3.8'

services:
  app:
    build: .
    container_name: lyrics-website-app
    ports:
      - "4321:4321"
    restart: always 

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    restart: always
    ports:
      - "4040:4040"
    volumes:
      - ./policy.yaml:/etc/ngrok/policy.yaml
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    command:
      - "http"
      - "app:4321"
      - "--traffic-policy-file"
      - "/etc/ngrok/policy.yaml"
    depends_on:
      - app
