version: '3.8'

services:
  web:
    build: . 
    container_name: lyrics-app 
    stdin_open: true
    tty: true 
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    ports:
      - "4321:4321"
